version: "3"

services:
  app_web:
    build: ./Web
    container_name: "django"
    volumes:
      - .:/lotokingsman
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app



  db:
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    container_name: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=dominik1998
      - MYSQL_PASSWORD=dominik1998
      - MYSQL_USER=wizex
      - MYSQL_DATABASE=LotoKingsMan
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
    ports:
      - '3008:3306'
    networks:
      - app

networks:
  app:
    driver: bridge
