# Generated by Django 4.0.5 on 2022-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна Пошта')),
                ('country', models.CharField(max_length=255, verbose_name='Країна')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('date_of_birth', models.DateField(verbose_name='Дата Народження')),
            ],
        ),
    ]
